name: Code Quality Check

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install htmlhint@latest --save-dev
          npm install stylelint@latest --save-dev
          npm install eslint@latest eslint-plugin-html@latest --save-dev

      - name: Lint HTML files
        run: npx htmlhint **/*.html

      - name: Lint CSS files
        run: npx stylelint --fix "**/*.css"

      - name: Lint JavaScript files
        run: npx eslint .

